// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zafkdidxjblujjmrifke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZmtkaWR4amJsdWpqbXJpZmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MzY3ODksImV4cCI6MjA3NTAxMjc4OX0.r7OB0oD1wsA2XExhSKgugU9LuRhBeHyTvWWAcvX-gpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});